CREATE TABLE Packages(
	PackageId INT IDENTITY NOT NULL PRIMARY KEY,
	PackageName VARCHAR(200) NOT NULL, 
	Description VARCHAR(1000) NOT NULL,
	PackageDurationType INT NOT NULL,
	Price DECIMAL(18, 2) NOT NULL,
	UserType INT NOT NULL,
	IsActive BIT NOT NULL,
	CreatedBy VARCHAR(100) NOT NULL,
	Created DATETIME NOT NULL,
	UpdatedBy VARCHAR(100) NOT NULL,
	Updated DATETIME NOT NULL
);
GO