IF OBJECT_ID(N'AdminLogin', N'U') IS NOT NULL
BEGIN
    DROP TABLE AdminLogin
END
GO

IF OBJECT_ID(N'Admin', N'U') IS NOT NULL
BEGIN
    DROP TABLE Admin
END
GO

CREATE TABLE Admin(
  AdminId INT IDENTITY  PRIMARY KEY  NOT NULL,
  Username VARCHAR(50) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  UserRole VARCHAR(25) NOT NULL,
  CreatedBy VARCHAR(50) NOT NULL,
  Created DATETIME NOT NULL,
  UpdatedBy VARCHAR(50) NOT NULL,
  Updated DATETIME NOT NULL
);
GO

CREATE TABLE AdminLogin(
    LoginId INT IDENTITY NOT NULL PRIMARY KEY,
	Username VARCHAR(50) NOT NULL,
	AdminId INT NOT NULL,
	LoginTime DATETIME NOT NULL,
	LogoutTime DATETIME NOT NULL,
	CONSTRAINT FK_Admin FOREIGN KEY (AdminId) REFERENCES Admin(AdminId)
);
GO

CREATE TABLE Employee(
	EmployeeId INT NOT NULL PRIMARY KEY IDENTITY,
	EmpName VARCHAR(50) NOT NULL,
	Role VARCHAR(30) NOT NULL,
	Address VARCHAR(100) NOT NULL,
	NIC VARCHAR(20) NOT NULL,
	DOB DATE NOT NULL,
	Email VARCHAR(70) NOT NULL,
	ContactNo VARCHAR(10) NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL,
	Created DATETIME NOT NULL,
	UpdatedBy VARCHAR(50) NOT NULL,
	updated DATETIME NOT NULL
);
GO


