IF OBJECT_ID(N'AdminLogin', N'U') IS NOT NULL
BEGIN
    DROP TABLE AdminLogin
END
GO

IF OBJECT_ID(N'Admin', N'U') IS NOT NULL
BEGIN
    DROP TABLE Admin
END
GO

CREATE TABLE Admin(
  AdminId INT IDENTITY  PRIMARY KEY  NOT NULL,
  Username VARCHAR(50) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  UserRole VARCHAR(25) NOT NULL,
  CreatedBy VARCHAR(50) NOT NULL,
  Created DATETIME NOT NULL,
  UpdatedBy VARCHAR(50) NOT NULL,
  Updated DATETIME NOT NULL
);
GO

CREATE TABLE AdminLogin(
    LoginId INT IDENTITY NOT NULL PRIMARY KEY,
	Username VARCHAR(50) NOT NULL,
	AdminId INT NOT NULL,
	LoginTime DATETIME NOT NULL,
	LogoutTime DATETIME NOT NULL,
	CONSTRAINT FK_Admin FOREIGN KEY (AdminId) REFERENCES Admin(AdminId)
);
GO


CREATE TABLE Employee(
	EmployeeId INT NOT NULL PRIMARY KEY IDENTITY,
	EmpName VARCHAR(50) NOT NULL,
	Role VARCHAR(30) NOT NULL,
	Address VARCHAR(100) NOT NULL,
	NIC VARCHAR(20) NOT NULL,
	DOB DATE NOT NULL,
	Email VARCHAR(70) NOT NULL,
	ContactNo VARCHAR(10) NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL,
	Created DATETIME NOT NULL,
	UpdatedBy VARCHAR(50) NOT NULL,
	updated DATETIME NOT NULL
);
GO

IF OBJECT_ID(N'BookingRoom', N'U') IS NOT NULL
BEGIN
    DROP TABLE BookingRoom
END
GO

IF OBJECT_ID(N'Room', N'U') IS NOT NULL
BEGIN
    DROP TABLE Room
END
GO

CREATE TABLE RoomCategory(
    CategoryId INT IDENTITY NOT NULL PRIMARY KEY,
	RoomName VARCHAR(200) NOT NULL,
	CountOfMaxGuest INT NOT NULL,
	Price FLOAT NOT NULL,
	DiscountPercent FLOAT NULL,
	DiscountPrice FLOAT NULL,
	Created DATETIME NOT NULL,
	CreatedBy VARCHAR(100) NOT NULL,
	Updated DATETIME NOT NULL,
	UpdatedBy VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Rooms(
	RoomId INT IDENTITY PRIMARY KEY NOT NULL,
	RoomNumber INT NOT NULL,
	RoomTypeId INT NOT NULL,
	RoomType VARCHAR(200) NOT NULL,
	IsBooked BIT NOT NULL,
	BookedFrom DATETIME NULL,
	BookedTo DATETIME NULL,
	CreatedBy VARCHAR(100) NOT NULL,
	Created DATETIME NOT NULL,
	UpdatedBy VARCHAR(100) NOT NULL,
	Updated DATETIME NOT NULL,
	CONSTRAINT FK_RoomCategory FOREIGN KEY (RoomTypeId) REFERENCES RoomCategory(CategoryId)
);
GO


CREATE TABLE BookingRooms(
    BookingRoomId INT IDENTITY NOT NULL PRIMARY KEY,
	BookingId INT NOT NULL,
	RoomId INT NOT NULL,
	CreatedBy VARCHAR(100) NOT NULL,
	Created DATETIME NOT NULL,
	UpdatedBy VARCHAR(100) NOT NULL,
	updated DATETIME NOT NULL
	CONSTRAINT FK_Booking FOREIGN KEY (BookingId) REFERENCES Bookings(BookingId),
	CONSTRAINT FK_Room FOREIGN KEY (RoomId) REFERENCES Rooms(RoomId)
);
GO


